### PR TITLE
Adds robot for extracting WARCs from WACZs.

### LINKED ISSUE #457: Add step to wasCrawlDissemination to handle WACZ files
This ticket is to support accessioning of WACZ files that will have been registered via one-time accessioning in WAS-Registrar-App. The shelve step in the accessionWF will have already have put the WACZ file in `/web-archiving-stacks` and the sdr-ingest-transfer step will have sent the WACZ file to preservation. 

Add a new step to the beginning of wasCrawlDisseminationWF, called get-warcs-from-wacz (open to better names, this is what is coming to mind now). It should:

1) Look for .wacz files in the `/web-archiving-stacks/data/collections/<collection-id>` dir. Extract the .warc.gz files from the .wacz file. In a WACZ, the warcs are gzipped and are in the `archive` directory.  (e.g. `unzip example.wacz archive/*.warc.gz -d <path>`)
2) Delete the .wacz file. 
2) Carry on with the workflow to index the warcs. 

To complete this work, you'll also need to update workflow-server-rails to have this new step in the wasCrawlDisseminationWF.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #457

## Why was this change made? 🤔
Use correct path when extracting WACZ files.

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from other services or writing to shared file systems, test that web archive seed and crawl accessioning works properly in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

**Comment by edsu** [comment]
I had to rebase off of main to get some dep update changes in order to deploy with cap. Testing this is on hold until we can start up Accessioning in QA again.

**Comment by edsu** [comment]
I think I've got the right branches deployed to was-robots1-qa, was-registration-app-qa but the WACZ file still seems to be getting copied instead of the WARC data:

See: https://argo-qa.stanford.edu/view/druid:xz326xk2574

```
was@was-pywb-qa:~$ ls /web-archiving-stacks/data/collections/gq319xk9269/xz/326/xk/2574/20220628121900-wikipedia.wacz
/web-archiving-stacks/data/collections/gq319xk9269/xz/326/xk/2574/20220628121900-wikipedia.wacz
was@was-pywb-qa:~$ file /web-archiving-stacks/data/collections/gq319xk9269/xz/326/xk/2574/20220628121900-wikipedia.wacz
/web-archiving-stacks/data/collections/gq319xk9269/xz/326/xk/2574/20220628121900-wikipedia.wacz: Zip archive data, at least v1.0 to extract
```

**Comment by justinlittman** [comment]
The workflow doesn't not contain the extract WARC step. I suspect that the workflow service was re-deployed over the branch that contained that step.

image

**Comment by edsu** [comment]
Thanks! It has been difficult keeping all the branches that need to be deployed for this in my head. I'll give it another try when I'm back at my laptop in the next could hours.

**Comment by edsu** [comment]
Ok, getting closer. It looks like the warc file is there:

```
was@was-pywb-qa:~$ ls -l /web-archiving-stacks/data/collections/gq319xk9269/nb/941/gx/7888/
total 3412
-rw-r--r-- 1 was was 3473636 Jun 28 10:06 20220628130300-wikipedia.wacz
```

But the CDXJ index wasn't written to:

```
was@was-pywb-qa:~$ ls -l /web-archiving-stacks/data/indexes/cdxj/
total 8901272
-rw-rw-r-- 1 was was          0 Jun 24 00:00 level0.cdxj
-rw-rw-r-- 1 was was     797436 Jun 24 00:00 level1.cdxj
-rw-r--r-- 1 was was          0 Jun 14 05:35 level2.cdxj
-rw-r--r-- 1 was was 9078346960 Jun 16 17:57 level3.cdxj
```

**Comment by edsu** [comment]
Gettin' closer. It looks like the WARC file is in place now:

```
was@was-pywb-qa:~$ ls -l /web-archiving-stacks/data/collections/gq319xk9269/rm/313/nz/3138/
total 3376
-rw-rw-r-- 1 was was 3439680 Jun 28 14:17 20220628171500-wikipedia-data.warc.gz
```

But the CDXJ index doesn't appear to have been updated?

```
was@was-pywb-qa:~$ ls -l /web-archiving-stacks/data/indexes/cdxj/
total 8901272
-rw-rw-r-- 1 was was          0 Jun 24 00:00 level0.cdxj
-rw-rw-r-- 1 was was     797436 Jun 24 00:00 level1.cdxj
-rw-r--r-- 1 was was          0 Jun 14 05:35 level2.cdxj
-rw-r--r-- 1 was was 9078346960 Jun 16 17:57 level3.cdxj
```

So it doesn't actually show up when trying to view the content.

**Comment by edsu** [comment]
I took a peek in the log `was@was-robots1-qa:~/was_robot_suite/current/log/cdx_indexer.log` and saw this (not timestamp but the file was written to today):

```
Exception in thread "main" java.lang.NullPointerException
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adaptInner(WARCRecordToSearchResultAdapter.java:93)
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adapt(WARCRecordToSearchResultAdapter.java:79)
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adapt(WARCRecordToSearchResultAdapter.java:53)
        at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:57)
        at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:55)
        at org.archive.wayback.resourcestore.indexer.IndexWorker.main(IndexWorker.java:216)
Exception in thread "main" java.lang.NullPointerException
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adaptInner(WARCRecordToSearchResultAdapter.java:93)
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adapt(WARCRecordToSearchResultAdapter.java:79)
        at org.archive.wayback.resourcestore.indexer.WARCRecordToSearchResultAdapter.adapt(WARCRecordToSearchResultAdapter.java:53)
        at org.archive.wayback.util.AdaptedIterator.hasNext(AdaptedIterator.java:57)
```

**Comment by edsu** [comment]
FWIW, I just tested one-time registration of WARCs and that continues to work.

**Comment by justinlittman** [comment]
Hmmm ... `jar/openwayback/bin/cdx-indexer /web-archiving-stacks/data/collections/gq319xk9269/rm/313/nz/3138/20220628171500-wikipedia-data.warc.gz` works.

**Comment by edsu** [comment]
Yes, the WARC file is in place. The indexes are not being updated though.

**Comment by edsu** [comment]
This is working now! https://argo-qa.stanford.edu/view/druid:yf654rv4725

**Review by edsu — APPROVED** [review]
Thanks for putting in the work to make this happen @justinlittman! I've tested both the WARC and WACZ accessioning and it is working.

**Pull request merged**
