### PR TITLE
make mods metadata location consistent with required value that is updated later

### LINKED ISSUE #257: wasSeedPreassembly should create/use MODS label "Archived website" instead of "Archived site"
**Describe the issue**
When accessioning a web archive seed, the wasSeedPreassembly workflow generates an initial MODS record that points to the SWAP URL for the seed:

```xml
<location displayLabel="Archived site">
    <url>https://swap.stanford.edu/*/https://www.j-oled.com/oled/</url>
</location>
```
The wasSeedPreassembly workflow uses this data to generate the thumbnail.

Once a web archive seed has been accessioned, the web archivist (or metadata staff, or a curator) imports new MODS that uses slightly different XML to point to the archived site:

```xml
  <location>
    <url usage="primary display">http://purl.stanford.edu/gb089bd2251</url>
    <url displayLabel="Archived website">https://swap.stanford.edu/*/http://naca.central.cranfield.ac.uk/</url>
  </location>
```

The sul-embed viewer for web archive seeds relies on this data for display and shows an error if the MODS doesn't conform to this structure.

These two `<location>` blocks should be made consistent. Since we ultimately want the second block displayed on the purl, I propose that we change the wasSeedPreassembly workflow to create and use the second `<location>` block from the start.

**User Impact**
Web archive seeds that have been accessioned but have not yet had their MODS updated show errors in the embed viewer on the purl.

**Additional context**
Example seed with auto-generated MODS:
https://argo.stanford.edu/view/druid:bd812qv1215

Example seed after MODS update:
https://argo.stanford.edu/view/gb089bd2251

**In the long run**
We should find some other part of the public XML to store this URL as it should never change. Putting it in the MODS means that a new metadata update, or an update to the template used for web archives, could unintentionally break things at any time.

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #257 

## How was this change tested?

Updated test

### CODE REVIEW

**Comment by peetucket** [comment]
@justinlittman any thoughts on this change?  are we missing anything that you can think of?

**Comment by justinlittman** [comment]
I believe that Searchworks uses this value to determine the SWAP link. @mejackreed ?

**Comment by justinlittman** [comment]
Oh wait, now I see the ticket. It was fixing that that motivated this change. Never mind.

**Comment by andrewjbtw** [comment]
I tested this on stage. There's one more change needed: the display label should be "Archived website" not "Archived site".

**Comment by peetucket** [comment]
Changed and redeployed to stage

**Pull request merged**
