### PR TITLE
Allow graceful resque restarts

### PR DESCRIPTION
**Pull request by mjgiarlo**
Not sure if puppet changes are needed to make this work though. Consulted @tallenaz. Cc: @peetucket @andrewjbtw

### CODE REVIEW

**Review by peetucket — APPROVED** [review]

**Review by ndushay — COMMENTED** [review]
Also - this repo needs github templates ...

was this tested?

convert to draft?

**Comment by mjgiarlo** [comment]
@ndushay :speech_balloon: 
> Also - this repo needs github templates ...

It has them. I deleted the boilerplate. :laughing: 

> was this tested?

Running in QA now.
 
> convert to draft?

ALL PRODUCTION ALL THE TIIIIIIIIIIIIME

**Comment by mjgiarlo** [comment]
@ndushay deployed fine in QA and stage without killing any workers. Re-review, pls?

**Review by jmartin-sul — COMMENTED** [review]
this LGTM based on a quick comparison with the two other projects i'm reasonably familiar with that use resque-pool (pres cat and pre-assembly).  i didn't see anything resque or resque-pool related in puppet, from a quick skim (and `cmd+F` for `resq`) in the puppet files for pres cat prod -02 or the pre-assembly prod VM.

**Comment by mjgiarlo** [comment]
@jmartin-sul indeed, @tallenaz has confirmed it won't need puppet changes. Thanks for looking into that.

**Comment by jmartin-sul** [comment]
ah, one other observation:  both of those projects use the `after 'deploy:restart'` for the `hotswap` call.  doubt that makes a difference, but noting just in case it was an oversight.

**Comment by mjgiarlo** [comment]
I have also put in DevOpsDocs PRs to reflect this change.

**Review by ndushay — APPROVED** [review]

**Pull request merged**
