### PR TITLE
per ActiveFedora update for Dor, change to Dor.find

### PR DESCRIPTION
**Pull request by ndushay**
I stumbled on this;  I fixed it.

### CODE REVIEW

**Comment by drh-stanford** [comment]
Looks like the specs need updating too -- see https://github.com/sul-dlss/was_robot_suite/blob/b8b0dac6aefe625922f588db3202157f18b7cdf2/spec/wasDissemination/robots/start_special_dissemination_spec.rb#L18 for example

**Comment by ndushay** [comment]
ya - i got them all but that one.  :-P

**Comment by ndushay** [comment]
"indecies" always made think of "indecencies"

**Comment by ndushay** [comment]
indecies always made me think of "indecencies"

**Pull request merged**
